CREATE TABLE IF NOT EXISTS knowledge_document (
    document_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    hotel_id BIGINT NULL,
    agent_id BIGINT NULL,
    title VARCHAR(255) NOT NULL,
    doc_type VARCHAR(64) NOT NULL DEFAULT 'policy',
    file_name VARCHAR(255) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    file_url VARCHAR(500) NULL,
    source_name VARCHAR(255) NOT NULL,
    collection_name VARCHAR(128) NOT NULL DEFAULT 'hotel_knowledge',
    file_hash VARCHAR(128) NULL,
    file_size BIGINT NULL,
    chunk_count INT NOT NULL DEFAULT 0,
    sync_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    sync_message VARCHAR(500) NULL,
    enabled TINYINT NOT NULL DEFAULT 1,
    last_sync_time DATETIME NULL,
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_knowledge_document_hotel_id (hotel_id),
    INDEX idx_knowledge_document_agent_id (agent_id),
    INDEX idx_knowledge_document_doc_type (doc_type),
    INDEX idx_knowledge_document_sync_status (sync_status),
    INDEX idx_knowledge_document_collection_name (collection_name)
);
